usb: gadget: android: Move to the new u_ether module
Also temporary include rndis.h in u_ether.c to adress build error
due to entire u_ether module is being compiled to the kernel
instead of include.

../drivers/usb/gadget/u_ether.c: In function 'gether_connect':
../drivers/usb/gadget/u_ether.c:1160:32: error: invalid application of 'sizeof' to incomplete type 'struct rndis_packet_msg_type'
link->header = kzalloc(sizeof(struct rndis_packet_msg_type),